Kredit/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Kredit'
admin.site.index_title = 'Welcome to Kredit'
admin.site.site_title = 'Kredit Administration'
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views

urlpatterns = [
    path('', views.loginUser, name='main'),
    path('identities/<str:img>', views.secure, name='secure'),
    path('open', views.open, name='open'),
    path('closed', views.closed, name='closed'),
    path('overdue', views.overdue, name='overdue'),
    path('search', views.search, name='search'),
    path('logout', views.logoutUser, name='logout'),
    path('entry/<int:key>', views.openEntry, name='entry'),
    path('delete_entry/<int:key>', views.deleteEntry, name='delete_entry'),
    path('delete_inst/<int:key>', views.deleteInst, name='delete_inst'),
    path('status_entry/<int:key>', views.statusEntry, name='status_entry'),
]

main/models.py
from django.db import models
from datetime import date

class Entries(models.Model):
    name = models.CharField(max_length=50)
    father = models.CharField(max_length=50)
    borrow_date = models.DateField(default=date.today)
    due_date = models.DateField()
    contact_one = models.CharField(max_length=15)
    contact_two = models.CharField(max_length=15, blank=True, null=True)
    principal = models.PositiveIntegerField()
    interest = models.DecimalField(max_digits=4, decimal_places=2)
    address = models.CharField(max_length=100)
    guarantor = models.CharField(max_length=50)
    contact_guar = models.CharField(max_length=15)
    entry_time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    identity = models.FileField(upload_to="identities")

    def __str__(self):
        return(self.name)
    

PAYMENT_TYPE = [
    ("GP", "GPay"),
    ("PH", "Phone Pay"),
    ("PA", "Paytm"),
    ("CA", "Cash"),
    ("BT", "Bank Transfer"),
]

class Installment(models.Model):
    entry = models.ForeignKey(Entries, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.PositiveIntegerField()
    date = models.DateField(default=date.today)
    pay_type = models.CharField(max_length=50, choices=PAYMENT_TYPE)

    def __str__(self):
        return(f'{self.entry.name} ({self.entry.id}) - {self.date}')

templates/basic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Dashboard</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />

    <style>
      a {
        text-decoration: none;
      }

      .point { cursor: pointer; }

      .custom-tooltip {
        --bs-tooltip-bg: var(--bs-primary);
        --bs-tooltip-color: var(--bs-white);
      }

      @media print {
        
      
          body * {
            visibility:hidden;
          }
        
        
          #table, #table * {
            visibility:visible;
            color: #000000;
            overflow: hidden;
          }
      
        }
      

    </style>
  </head>
  <body data-bs-theme="dark">
    <nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/open">Kredit Dashboard</a>
        <ul
          class="navbar-nav navbar-nav-scroll me-auto mb-2 mb-lg-0 col justify-content-center flex-row"
        >
          <li class="nav-item">
              <a class="btn {%block btnopen%}btn-outline-success{%endblock btnopen%} mx-2" href="/open" role="button">Open</a>
          </li>
          <li class="nav-item">
              <a class="btn {%block btnoverdue%}btn-outline-warning{%endblock btnoverdue%} mx-2" href="/overdue" role="button">Overdue</a>
          </li>
          <li class="nav-item">
              <a class="btn {%block btnclosed%}btn-outline-danger{%endblock btnclosed%} mx-2" href="/closed" role="button">Closed</a>
          </li>
        </ul>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">

          <form class="d-flex" role="search" method="get" action="/search">
            <input
              class="form-control"
              type="search"
              placeholder="Search Anything"
              aria-label="Search"
              name = "query"
              data-bs-toggle="tooltip" data-bs-placement="left" data-bs-custom-class="custom-tooltip" data-bs-title="Date Format: [YYYY-MM-DD]"
            />
            <button class="btn btn-outline-primary ms-2 me-2" type="submit">
              Search
            </button>
          </form>
          <button type="button" onclick="window.print()" class="btn btn-info m-2">PDF</button>
          {% if perms.main.add_entries %}
          <button type="button" class="btn btn-success m-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Add
          </button>
          {%endif%}
          <a class="btn btn-danger m-2" href="/logout" role="button">Logout</a>
        </div>
      </div>
    </nav>
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show text-center" role="alert">{{message}}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
    {% endfor %}
    {% if entries %}
    
    <div class="table-responsive" id="table">
    <table class="table table-dark table-hover">
      <thead class="table-light">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Father</th>
          <th scope="col">Contact</th>
          <th scope="col">Borrow</th>
          <th scope="col">Principal</th>
          <th scope="col">Guarantor</th>
          <th scope="col">Address</th>
        </tr>
      </thead>
      <tbody>
         {% block table %}{% endblock table %}
      </tbody>
    </table>
  </div>
    {% endif %}




<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Add New Entry</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" action="/open" enctype="multipart/form-data">
          {% csrf_token %}


   {{form}}


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    >
  </script>
  <script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
  </script>
  </body>
</html>

templates/closed.html
{% extends 'basic.html' %} 
{% block btnclosed %}btn-danger{% endblock btnclosed %}
{% block table %}{% for entry in entries %}
{% if entry.status == True %}
<tr onclick="window.location='{% url 'entry' entry.id%}'" class="point">
  <th scope="row">{{entry.id}}</th>
  <td>{{entry.name}}</td>
  <td>{{entry.father}}</td>
  <td><a href="tel:{{entry.contact_one}}">{{entry.contact_one}}</a></td>
  <td>{{entry.borrow_date}}</td>
  <td>₹{{entry.principal}}</td>
  <td>{{entry.guarantor}}</td>
  <td style="max-width: 200px">{{entry.address}}</td>

</tr>
{% endif %}

{% endfor %} {% endblock table %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Kredit - Sign In</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />

  
    <meta name="theme-color" content="#712cf9" />

    <style>
      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }

      html,
      body {
        height: 100%;
      }

      .form-signin {
        max-width: 330px;
        padding: 1rem;
      }

      .form-signin .form-floating:focus-within {
        z-index: 2;
      }

      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }

      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
    </style>
  </head>

  <body
    class="d-flex align-items-center py-4 bg-body-tertiary text-center"
    data-bs-theme="dark"
  >
    <main class="form-signin w-100 m-auto">
      <img
        class="m-5"
        style="scale: 2"
        src="/static/logo.png"
        alt=""
        width="72"
        height="57"
      />

      {% for message in messages %}
      <div class="alert alert-{{message.tags}}" role="alert">{{message}}</div>
      {% endfor %}

      <form method="post" action="/">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Please Sign In</h1>

        <div class="form-floating">
          <input
            style="margin-bottom: 4px"
            type="text"
            name="username"
            class="form-control"
            id="floatingInput"
            placeholder="Username"
          />
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input
            style="margin-top: 4px"
            style="margin-bottom: 4px"
            type="password"
            name="password"
            class="form-control"
            id="floatingPassword"
            placeholder="Password"
          />
          <label for="floatingPassword">Password</label>
        </div>
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <button class="btn btn-primary w-100 py-2" type="submit">
          Sign in
        </button>
      </form>
    </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/open.html
{% extends 'basic.html' %}
{% block btnopen %}btn-success{% endblock btnopen %}
{% block table %}{% for entry in entries %}
{% if entry.status == False %}
<tr onclick="window.location='{% url 'entry' entry.id%}'" class="point">
  <th scope="row">{{entry.id}}</th>
  <td>{{entry.name}}</td>
  <td>{{entry.father}}</td>
  <td><a href="tel:{{entry.contact_one}}">{{entry.contact_one}}</a></td>
  <td>{{entry.borrow_date}}</td>
  <td>₹{{entry.principal}}</td>
  <td>{{entry.guarantor}}</td>
  <td style="max-width: 200px">{{entry.address}}</td>
</tr>
{% endif %}

{% endfor %} {% endblock table %}

templates/overdue.html
{% extends 'basic.html' %}
{% block btnoverdue %}btn-warning{% endblock btnoverdue %}
{% load due %}
{% block table %}{% for entry in entries %}
{% if entry.status == False and entry|due == True %}
<tr onclick="window.location='{% url 'entry' entry.id%}'" class="point">
  <th scope="row">{{entry.id}}</th>
  <td>{{entry.name}}</td>
  <td>{{entry.father}}</td>
  <td><a href="tel:{{entry.contact_one}}">{{entry.contact_one}}</a></td>
  <td>{{entry.borrow_date}}</td>
  <td>₹{{entry.principal}}</td>
  <td>{{entry.guarantor}}</td>
  <td style="max-width: 200px">{{entry.address}}</td>
</tr>
{% endif %}
{% endfor %} {% endblock table %}

templates/search.html
{% extends 'basic.html' %}
{% block table %}{% for entry in entries %}
<tr onclick="window.location='{% url 'entry' entry.id%}'" class="point">
  <th scope="row">{{entry.id}}</th>
  <td>{{entry.name}}</td>
  <td>{{entry.father}}</td>
  <td><a href="tel:{{entry.contact_one}}">{{entry.contact_one}}</a></td>
  <td>{{entry.borrow_date}}</td>
  <td>₹{{entry.principal}}</td>
  <td>{{entry.guarantor}}</td>
  <td style="max-width: 200px">{{entry.address}}</td>
</tr>

{% endfor %} {% endblock table %}